CREATE TABLE [dbo].[Book]
(
	[BookId] INT NOT NULL IDENTITY PRIMARY KEY, 
    [ISBN10] NCHAR(10) NULL, 
    [ISBN13] NCHAR(13) NULL, 
    [ASIN10] NCHAR(10) NULL,
)
GO;

CREATE UNIQUE NONCLUSTERED INDEX IDX_ISBN13_NOTNULL
ON [dbo].[Book](ISBN13)
WHERE ISBN13 IS NOT NULL
GO;

CREATE UNIQUE NONCLUSTERED INDEX IDX_ASIN_NOTNULL
ON [dbo].[Book]([ASIN10])
WHERE [ASIN10] IS NOT NULL
GO;
