// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VanillaDb.DataProviders
{
    using System;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using VanillaDb;
    using VanillaDb.Models;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class SqlDataProvider : SqlDataProviderBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("// <copyright file=\"");
            
            #line 9 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateName()));
            
            #line default
            #line hidden
            this.Write(".cs\" company=\"");
            
            #line 9 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Company));
            
            #line default
            #line hidden
            this.Write("\">\r\n// Copyright (c) ");
            
            #line 10 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Company));
            
            #line default
            #line hidden
            this.Write(@". All rights reserved.
// </copyright>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace ");
            
            #line 20 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Namespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 20 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.TableAlias));
            
            #line default
            #line hidden
            this.Write(@"
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.Extensions.Logging;
    using Microsoft.Extensions.Logging.Abstractions;

    /// <summary>SQL implementation of data provider interface for ");
            
            #line 31 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write(" data.</summary>\r\n    /// <seealso cref=\"");
            
            #line 32 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Namespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 32 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.TableAlias));
            
            #line default
            #line hidden
            this.Write(".I");
            
            #line 32 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write("DataProvider\" />\r\n    public partial class ");
            
            #line 33 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateName()));
            
            #line default
            #line hidden
            this.Write(" : I");
            
            #line 33 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write("DataProvider\r\n    {\r\n        private ILogger Log { get; set; }\r\n\r\n        /// <su" +
                    "mmary>Initializes a new instance of the <see cref=\"");
            
            #line 37 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateName()));
            
            #line default
            #line hidden
            this.Write("\"/> class.</summary>\r\n        /// <param name=\"connectionString\">The connection s" +
                    "tring.</param>\r\n        /// <param name=\"logger\">The logger for this instance.</" +
                    "param>\r\n        public ");
            
            #line 40 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateName()));
            
            #line default
            #line hidden
            this.Write("(string connectionString, ILogger<");
            
            #line 40 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateName()));
            
            #line default
            #line hidden
            this.Write(@"> logger)
        {
            this.Log = (ILogger)logger ?? NullLogger.Instance;
            this.ConnectionString = connectionString;
        }

        /// <summary>Gets or sets the connection string.</summary>
        /// <value>The connection string.</value>
        private string ConnectionString { get; set; }
");
            
            #line 49 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

    // Generate the GetAll method if configured
    if (Table.Config.GetAll)
    {

            
            #line default
            #line hidden
            this.Write("\r\n        /// <summary>Gets the data for all ");
            
            #line 55 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write("(s) from the ");
            
            #line 55 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.TableName));
            
            #line default
            #line hidden
            this.Write(" table.</summary>\r\n        /// <returns>Enumerable of ");
            
            #line 56 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write(" Data Model or null if not found.</returns>\r\n        public async Task<IEnumerabl" +
                    "e<");
            
            #line 57 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.GetDataModelName()));
            
            #line default
            #line hidden
            this.Write(">> GetAll()\r\n        {\r\n            var ");
            
            #line 59 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RecordCamel));
            
            #line default
            #line hidden
            this.Write("Data = new List<");
            
            #line 59 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write("DataModel>();\r\n            using (var connection = new SqlConnection(this.Connect" +
                    "ionString))\r\n            {\r\n                var procName = \"[");
            
            #line 62 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 62 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.GetGetAllProcName()));
            
            #line default
            #line hidden
            this.Write(@"]"";
                using (var command = new SqlCommand(procName))
                {
                    Log.LogInformation(""Invoking Stored Procedure {0}."", procName);
                    command.CommandType = CommandType.StoredProcedure;
                    command.Connection = connection;

                    connection.Open();
                    var reader = await command.ExecuteReaderAsync();
                    if (reader.HasRows)
                    {
                        while (reader.Read())
                        {
                            var data = Parse");
            
            #line 75 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write("DataModel(reader);\r\n                            ");
            
            #line 76 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RecordCamel));
            
            #line default
            #line hidden
            this.Write("Data.Add(data);\r\n                        }\r\n\r\n                        // consume " +
                    "any trailing pieces\r\n                        while (reader.NextResult()) {}\r\n   " +
                    "                 }\r\n                }\r\n            }\r\n\r\n            return ");
            
            #line 85 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RecordCamel));
            
            #line default
            #line hidden
            this.Write("Data;\r\n        }\r\n");
            
            #line 87 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

    }

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 91 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

    // Generate the GetBy-Index and GetBy-Index-Bulk methods for each index
    foreach (IndexModel index in Indexes)
    {

            
            #line default
            #line hidden
            this.Write("        /// <summary>Gets the data for the ");
            
            #line 96 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write(" with the given ");
            
            #line 96 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index.ReadableFields()));
            
            #line default
            #line hidden
            this.Write(".</summary>\r\n        ");
            
            #line 97 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index.GetByIndexParamsXmlComments()));
            
            #line default
            #line hidden
            this.Write("\r\n        /// <returns>");
            
            #line 98 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write(" Data Model or null if not found</returns>\r\n        public async Task<");
            
            #line 99 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index.GetByIndexReturnType()));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 99 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index.GetByIndexMethodName()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 99 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index.GetByIndexMethodParams()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n");
            
            #line 101 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

        foreach (FieldModel field in index.Fields.Where(f => !f.IsNullable))
        {
            if (field.FieldType.FieldType == typeof(string))
            {

            
            #line default
            #line hidden
            this.Write("            if (string.IsNullOrWhiteSpace(");
            
            #line 107 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("))\r\n            {\r\n                throw new ArgumentNullException(nameof(");
            
            #line 109 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("));\r\n            }\r\n\r\n");
            
            #line 112 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

            }

            
            #line default
            #line hidden
            
            #line 115 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

            if (field.IsIdentity && field.FieldType.FieldType == typeof(int))
            {

            
            #line default
            #line hidden
            this.Write("            if (");
            
            #line 119 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" < 1)\r\n            {\r\n                throw new InvalidOperationException($\"{");
            
            #line 121 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("} is not a valid ");
            
            #line 121 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));
            
            #line default
            #line hidden
            this.Write("\");\r\n            }\r\n\r\n");
            
            #line 124 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

            }
        }

            
            #line default
            #line hidden
            this.Write("            var ");
            
            #line 128 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RecordCamel));
            
            #line default
            #line hidden
            this.Write("Data = new List<");
            
            #line 128 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write("DataModel>();\r\n            using (var connection = new SqlConnection(this.Connect" +
                    "ionString))\r\n            {\r\n                var procName = \"[");
            
            #line 131 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 131 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index.GetByIndexProcName(TemporalTypes.Default)));
            
            #line default
            #line hidden
            this.Write("]\";\r\n                ");
            
            #line 132 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

                if (index.Table.IsTemporal && index.Table.Config.TemporalGetAll.Value)
                {
                
            
            #line default
            #line hidden
            this.Write("                if (temporalOperator == TemporalTypes.All)\r\n                {\r\n  " +
                    "                  procName = \"[");
            
            #line 138 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 138 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index.GetByIndexProcName(TemporalTypes.All)));
            
            #line default
            #line hidden
            this.Write("]\";\r\n                }\r\n\r\n                ");
            
            #line 141 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

                }
                
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 144 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

                if (index.Table.IsTemporal && index.Table.Config.TemporalGetAsOf.Value)
                {
                
            
            #line default
            #line hidden
            this.Write("                if (temporalOperator == TemporalTypes.AsOf)\r\n                {\r\n " +
                    "                   procName = \"[");
            
            #line 150 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 150 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index.GetByIndexProcName(TemporalTypes.AsOf)));
            
            #line default
            #line hidden
            this.Write("]\";\r\n                }\r\n\r\n                ");
            
            #line 153 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

                }
                
            
            #line default
            #line hidden
            this.Write(@"                using (var command = new SqlCommand(procName))
                {
                    Log.LogInformation(""Invoking Stored Procedure {0}."", procName);
                    command.CommandType = CommandType.StoredProcedure;
                    command.Connection = connection;
                    ");
            
            #line 161 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateGetByIndexAddParametersCode(index.Parameters())));
            
            #line default
            #line hidden
            this.Write("\r\n                    ");
            
            #line 162 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

                    if (index.Table.IsTemporal && index.Table.Config.TemporalGetAsOf.Value)
                    {
                    
            
            #line default
            #line hidden
            this.Write("                    if (temporalOperator == TemporalTypes.AsOf)\r\n                " +
                    "    {\r\n                        command.Parameters.AddWithValue(\"@asOfDate\", asOf" +
                    "Date);\r\n                    }\r\n                    ");
            
            #line 170 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

                    }
                    
            
            #line default
            #line hidden
            this.Write(@"
                    connection.Open();
                    var reader = await command.ExecuteReaderAsync();
                    if (reader.HasRows)
                    {
                        while (reader.Read())
                        {
                            var data = Parse");
            
            #line 180 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write("DataModel(reader);\r\n                            ");
            
            #line 181 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RecordCamel));
            
            #line default
            #line hidden
            this.Write("Data.Add(data);\r\n                        }\r\n\r\n                        // consume " +
                    "any trailing pieces\r\n                        while (reader.NextResult()) {}\r\n   " +
                    "                 }\r\n                }\r\n            }\r\n\r\n");
            
            #line 190 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

            if (index.IsUnique && (!Table.IsTemporal || !Table.Config.TemporalGetAll.Value))
            {

            
            #line default
            #line hidden
            this.Write("            return ");
            
            #line 194 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RecordCamel));
            
            #line default
            #line hidden
            this.Write("Data.FirstOrDefault();\r\n");
            
            #line 195 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

            }
            else
            {

            
            #line default
            #line hidden
            this.Write("            return ");
            
            #line 200 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RecordCamel));
            
            #line default
            #line hidden
            this.Write("Data;\r\n");
            
            #line 201 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

            }

            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        /// <summary>Gets the data for the ");
            
            #line 206 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write("(s) with the given collection of ");
            
            #line 206 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index.ReadableFields()));
            
            #line default
            #line hidden
            this.Write(".</summary>\r\n        ");
            
            #line 207 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index.BulkGetByIndexParamsXmlComments()));
            
            #line default
            #line hidden
            this.Write("\r\n        /// <returns>");
            
            #line 208 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write(" Data Model or null if not found.</returns>\r\n        public async Task<IEnumerabl" +
                    "e<");
            
            #line 209 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write("DataModel>> ");
            
            #line 209 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index.GetByIndexMethodName()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 209 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index.BulkGetByIndexMethodParams()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n");
            
            #line 211 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

        foreach (FieldModel field in index.Fields)
        {

            
            #line default
            #line hidden
            this.Write("            if (");
            
            #line 215 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("s == null || !");
            
            #line 215 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("s.Any())\r\n            {\r\n                throw new ArgumentNullException(nameof(");
            
            #line 217 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("s));\r\n            }\r\n\r\n");
            
            #line 220 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

        }

            
            #line default
            #line hidden
            this.Write("            // Create an in-memory datatable with all of the field values\r\n      " +
                    "      var idDataTable = new DataTable();\r\n            ");
            
            #line 225 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateInMemoryDataColumns(index.Fields)));
            
            #line default
            #line hidden
            this.Write("\r\n            for (var i = 0; i < ");
            
            #line 226 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index.Fields.ElementAt(0).FieldName.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("s.Count(); i++)\r\n            {\r\n                ");
            
            #line 228 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateInMemoryRowCreation(index.Fields)));
            
            #line default
            #line hidden
            this.Write("\r\n            }\r\n\r\n            var ");
            
            #line 231 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RecordCamel));
            
            #line default
            #line hidden
            this.Write("Data = new List<");
            
            #line 231 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write("DataModel>();\r\n            using (var connection = new SqlConnection(this.Connect" +
                    "ionString))\r\n            {\r\n                var procName = \"[");
            
            #line 234 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 234 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index.BulkGetByIndexProcName(TemporalTypes.Default)));
            
            #line default
            #line hidden
            this.Write("]\";\r\n                ");
            
            #line 235 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

                if (index.Table.IsTemporal && index.Table.Config.TemporalGetAll.Value)
                {
                
            
            #line default
            #line hidden
            this.Write("                if (temporalOperator == TemporalTypes.All)\r\n                {\r\n  " +
                    "                  procName = \"[");
            
            #line 241 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 241 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index.BulkGetByIndexProcName(TemporalTypes.All)));
            
            #line default
            #line hidden
            this.Write("]\";\r\n                }\r\n\r\n                ");
            
            #line 244 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

                }
                
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 247 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

                if (index.Table.IsTemporal && index.Table.Config.TemporalGetAsOf.Value)
                {
                
            
            #line default
            #line hidden
            this.Write("                if (temporalOperator == TemporalTypes.AsOf)\r\n                {\r\n " +
                    "                   procName = \"[");
            
            #line 253 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 253 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index.BulkGetByIndexProcName(TemporalTypes.AsOf)));
            
            #line default
            #line hidden
            this.Write("]\";\r\n                }\r\n\r\n                ");
            
            #line 256 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

                }
                
            
            #line default
            #line hidden
            this.Write(@"
                using (var command = new SqlCommand(procName))
                {
                    Log.LogInformation(""Invoking Stored Procedure {0}."", procName);
                    command.CommandType = CommandType.StoredProcedure;
                    command.Connection = connection;

                    // Create the Stored Procedure Parameter and set to Type_IdTable
                    var idsParam = command.Parameters.AddWithValue(""");
            
            #line 267 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateBulkProcParameter(index)));
            
            #line default
            #line hidden
            this.Write("\", idDataTable);\r\n                    idsParam.SqlDbType = SqlDbType.Structured;\r" +
                    "\n                    idsParam.TypeName = \"");
            
            #line 269 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index.GetBulkTypeIdTable()));
            
            #line default
            #line hidden
            this.Write("\";\r\n                    ");
            
            #line 270 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

                    if (index.Table.IsTemporal && index.Table.Config.TemporalGetAsOf.Value)
                    {
                    
            
            #line default
            #line hidden
            this.Write("                    if (temporalOperator == TemporalTypes.AsOf)\r\n                " +
                    "    {\r\n                        command.Parameters.AddWithValue(\"@asOfDate\", asOf" +
                    "Date);\r\n                    }\r\n                    ");
            
            #line 278 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

                    }
                    
            
            #line default
            #line hidden
            this.Write(@"

                    connection.Open();
                    var reader = await command.ExecuteReaderAsync();
                    if (reader.HasRows)
                    {
                        while (reader.Read())
                        {
                            var data = Parse");
            
            #line 289 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write("DataModel(reader);\r\n                            ");
            
            #line 290 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RecordCamel));
            
            #line default
            #line hidden
            this.Write("Data.Add(data);\r\n                        }\r\n\r\n                        // consume " +
                    "any trailing pieces\r\n                        while (reader.NextResult()) {}\r\n   " +
                    "                 }\r\n                }\r\n            }\r\n\r\n            return ");
            
            #line 299 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RecordCamel));
            
            #line default
            #line hidden
            this.Write("Data;\r\n        }\r\n\r\n");
            
            #line 302 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

    }

            
            #line default
            #line hidden
            
            #line 305 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

    // Generate the Insert method if configured
    if (Table.Config.Insert)
    {

            
            #line default
            #line hidden
            this.Write("        /// <summary>Inserts the given ");
            
            #line 310 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write(" data model into the ");
            
            #line 310 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write(" table.</summary>\r\n        /// <param name=\"");
            
            #line 311 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RecordCamel));
            
            #line default
            #line hidden
            this.Write("Data\">The ");
            
            #line 311 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RecordLower));
            
            #line default
            #line hidden
            this.Write(" data to insert.</param>\r\n        /// <returns>The ID of the inserted ");
            
            #line 312 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write(" record if a primary key exists, otherwise, -1.</returns>\r\n        public async T" +
                    "ask<int> Insert(");
            
            #line 313 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write("DataModel ");
            
            #line 313 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RecordCamel));
            
            #line default
            #line hidden
            this.Write("Data)\r\n        {\r\n            if (");
            
            #line 315 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RecordCamel));
            
            #line default
            #line hidden
            this.Write("Data == null)\r\n            {\r\n                throw new ArgumentNullException(nam" +
                    "eof(");
            
            #line 317 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RecordCamel));
            
            #line default
            #line hidden
            this.Write(@"Data));
            }

            if (string.IsNullOrWhiteSpace(this.ConnectionString))
            {
                throw new InvalidOperationException(""Connection String is null.  Insert operation cannot be performed."");
            }
            ");
            
            #line 324 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

            if (Table.HasPrimaryKey && PrimaryKey.IsIdentity)
            {
            
            
            #line default
            #line hidden
            this.Write("\r\n            if (");
            
            #line 329 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RecordCamel));
            
            #line default
            #line hidden
            this.Write("Data.");
            
            #line 329 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKey.FieldName));
            
            #line default
            #line hidden
            this.Write(" > 0)\r\n            {\r\n                throw new InvalidOperationException(\"Unable" +
                    " to insert ");
            
            #line 331 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write(" Data that already has a ");
            
            #line 331 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKey.FieldName));
            
            #line default
            #line hidden
            this.Write(".\");\r\n            }\r\n            ");
            
            #line 333 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

            }
            
            
            #line default
            #line hidden
            this.Write("\r\n            var newId = -1;\r\n            using (var connection = new SqlConnect" +
                    "ion(this.ConnectionString))\r\n            {\r\n                var procName = \"[");
            
            #line 340 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 340 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.GetInsertProcName()));
            
            #line default
            #line hidden
            this.Write(@"]"";
                using (var command = new SqlCommand(procName))
                {
                    Log.LogInformation(""Invoking Stored Procedure {0}."", procName);
                    command.CommandType = CommandType.StoredProcedure;
                    command.Connection = connection;
                    ");
            
            #line 346 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateInsertProcParams()));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n                    connection.Open();\r\n                    var reader = awai" +
                    "t command.ExecuteReaderAsync();\r\n                    if (reader.HasRows)\r\n      " +
                    "              {\r\n                        while (reader.Read())\r\n                " +
                    "        {\r\n");
            
            #line 354 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

                            if (Table.HasPrimaryKey)
                            {

            
            #line default
            #line hidden
            this.Write("                            newId = (int)reader[\"");
            
            #line 358 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKey.FieldName));
            
            #line default
            #line hidden
            this.Write("\"];\r\n");
            
            #line 359 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

                            }

            
            #line default
            #line hidden
            this.Write("                        }\r\n\r\n                        // consume any trailing piec" +
                    "es\r\n                        while (reader.NextResult()) {}\r\n                    " +
                    "}\r\n                }\r\n            }\r\n\r\n            return newId;\r\n        }\r\n\r\n");
            
            #line 373 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

    }

            
            #line default
            #line hidden
            
            #line 376 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

    // Generate the Update method if configured
    if (Table.Config.Update)
    {

            
            #line default
            #line hidden
            this.Write("        /// <summary>Updates the given ");
            
            #line 381 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write(" data model in the ");
            
            #line 381 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write(" table.</summary>\r\n        /// <param name=\"");
            
            #line 382 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RecordCamel));
            
            #line default
            #line hidden
            this.Write("Data\">The ");
            
            #line 382 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RecordLower));
            
            #line default
            #line hidden
            this.Write(" data to update.</param>\r\n        /// <returns>The number of records affected by " +
                    "the update.</returns>\r\n        public async Task<int> Update(");
            
            #line 384 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write("DataModel ");
            
            #line 384 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RecordCamel));
            
            #line default
            #line hidden
            this.Write("Data)\r\n        {\r\n            if (");
            
            #line 386 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RecordCamel));
            
            #line default
            #line hidden
            this.Write("Data == null)\r\n            {\r\n                throw new ArgumentNullException(nam" +
                    "eof(");
            
            #line 388 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RecordCamel));
            
            #line default
            #line hidden
            this.Write(@"Data));
            }

            if (string.IsNullOrWhiteSpace(this.ConnectionString))
            {
                throw new InvalidOperationException(""Connection String is null.  Insert operation cannot be performed."");
            }

            if (");
            
            #line 396 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RecordCamel));
            
            #line default
            #line hidden
            this.Write("Data.");
            
            #line 396 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKey.FieldName));
            
            #line default
            #line hidden
            this.Write(" <= 0)\r\n            {\r\n                throw new InvalidOperationException(\"A val" +
                    "id ");
            
            #line 398 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKey.FieldName));
            
            #line default
            #line hidden
            this.Write(" must be provided to update.\");\r\n            }\r\n\r\n            var affectedRows = " +
                    "0;\r\n            using (var connection = new SqlConnection(this.ConnectionString)" +
                    ")\r\n            {\r\n                var procName = \"[");
            
            #line 404 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 404 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.GetUpdateProcName()));
            
            #line default
            #line hidden
            this.Write(@"]"";
                using (var command = new SqlCommand(procName))
                {
                    Log.LogInformation(""Invoking Stored Procedure {0}."", procName);
                    command.CommandType = CommandType.StoredProcedure;
                    command.Connection = connection;
                    ");
            
            #line 410 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateUpdateProcParams()));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n                    connection.Open();\r\n                    affectedRows = aw" +
                    "ait command.ExecuteNonQueryAsync();\r\n                }\r\n            }\r\n\r\n       " +
                    "     return affectedRows;\r\n        }\r\n\r\n");
            
            #line 420 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

    }

            
            #line default
            #line hidden
            
            #line 423 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

    // Generate the Delete method if configured
    if (Table.Config.Delete)
    {

            
            #line default
            #line hidden
            this.Write("        /// <summary>Deletes record with the given ");
            
            #line 428 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKey.FieldName));
            
            #line default
            #line hidden
            this.Write(" from the ");
            
            #line 428 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.TableName));
            
            #line default
            #line hidden
            this.Write(" table.</summary>\r\n        /// <param name=\"");
            
            #line 429 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKey.GetCodeParamName()));
            
            #line default
            #line hidden
            this.Write("\">The ");
            
            #line 429 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKey.FieldName));
            
            #line default
            #line hidden
            this.Write(".</param>\r\n        public async Task<int> Delete(int ");
            
            #line 430 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKey.GetCodeParamName()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            if (");
            
            #line 432 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKey.GetCodeParamName()));
            
            #line default
            #line hidden
            this.Write(" <= 0)\r\n            {\r\n                throw new InvalidOperationException(\"A val" +
                    "id ");
            
            #line 434 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKey.FieldName));
            
            #line default
            #line hidden
            this.Write(" must be provided to delete.\");\r\n            }\r\n\r\n            var affectedRows = " +
                    "0;\r\n            using (var connection = new SqlConnection(this.ConnectionString)" +
                    ")\r\n            {\r\n                var procName = \"[");
            
            #line 440 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 440 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.GetDeleteProcName()));
            
            #line default
            #line hidden
            this.Write(@"]"";
                using (var command = new SqlCommand(procName))
                {
                    Log.LogInformation(""Invoking Stored Procedure {0}."", procName);
                    command.CommandType = CommandType.StoredProcedure;
                    command.Connection = connection;
                    command.Parameters.AddWithValue(""");
            
            #line 446 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKey.GetParamName()));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 446 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKey.GetCodeParamName()));
            
            #line default
            #line hidden
            this.Write(@");

                    connection.Open();
                    affectedRows = await command.ExecuteNonQueryAsync();
                }
            }

            return affectedRows;
        }

        /// <summary>Deletes the records with the given ");
            
            #line 456 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKey.FieldName));
            
            #line default
            #line hidden
            this.Write("s from the ");
            
            #line 456 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.TableName));
            
            #line default
            #line hidden
            this.Write(" table.</summary>\r\n        /// <param name=\"");
            
            #line 457 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKey.GetCodeParamName()));
            
            #line default
            #line hidden
            this.Write("s\">The ");
            
            #line 457 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKey.FieldName));
            
            #line default
            #line hidden
            this.Write("s.</param>\r\n        public async Task<int> Delete(IEnumerable<int> ");
            
            #line 458 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKey.GetCodeParamName()));
            
            #line default
            #line hidden
            this.Write("s)\r\n        {\r\n            if (");
            
            #line 460 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKey.GetCodeParamName()));
            
            #line default
            #line hidden
            this.Write("s == null)\r\n            {\r\n                throw new ArgumentNullException(nameof" +
                    "(");
            
            #line 462 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKey.GetCodeParamName()));
            
            #line default
            #line hidden
            this.Write("s));\r\n            }\r\n\r\n            if (!");
            
            #line 465 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKey.GetCodeParamName()));
            
            #line default
            #line hidden
            this.Write("s.Any())\r\n            {\r\n                throw new ArgumentException(\"At least on" +
                    "e ");
            
            #line 467 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKey.FieldName));
            
            #line default
            #line hidden
            this.Write(" must be provided to delete.\", nameof(");
            
            #line 467 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKey.GetCodeParamName()));
            
            #line default
            #line hidden
            this.Write("s));\r\n            }\r\n\r\n            if (");
            
            #line 470 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKey.GetCodeParamName()));
            
            #line default
            #line hidden
            this.Write("s.Any(i => i <= 0))\r\n            {\r\n                throw new InvalidOperationExc" +
                    "eption(\"All ");
            
            #line 472 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKey.FieldName));
            
            #line default
            #line hidden
            this.Write("s must be valid to delete.\");\r\n            }\r\n\r\n            // Create an in-memor" +
                    "y datatable with the primary key values\r\n            var idDataTable = new DataT" +
                    "able();\r\n            idDataTable.Columns.Add(new DataColumn(\"");
            
            #line 477 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKey.FieldName));
            
            #line default
            #line hidden
            this.Write("\"));\r\n            for (var i = 0; i < ");
            
            #line 478 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKey.GetCodeParamName()));
            
            #line default
            #line hidden
            this.Write("s.Count(); i++)\r\n            {\r\n                idDataTable.Rows.Add(");
            
            #line 480 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKey.GetCodeParamName()));
            
            #line default
            #line hidden
            this.Write("s.ElementAt(i));\r\n            }\r\n\r\n            var affectedRows = 0;\r\n           " +
                    " using (var connection = new SqlConnection(this.ConnectionString))\r\n            " +
                    "{\r\n                var procName = \"[");
            
            #line 486 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 486 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.GetDeleteBulkProcName()));
            
            #line default
            #line hidden
            this.Write(@"]"";
                using (var command = new SqlCommand(procName))
                {
                    Log.LogInformation(""Invoking Stored Procedure {0}."", procName);
                    command.CommandType = CommandType.StoredProcedure;
                    command.Connection = connection;

                    // Create the Stored Procedure Parameter and set to the Type table
                    var idsParam = command.Parameters.AddWithValue(""");
            
            #line 494 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKey.GetParamName()));
            
            #line default
            #line hidden
            this.Write("s\", idDataTable);\r\n                    idsParam.SqlDbType = SqlDbType.Structured;" +
                    "\r\n                    idsParam.TypeName = \"");
            
            #line 496 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKeyIndex.GetBulkTypeIdTable()));
            
            #line default
            #line hidden
            this.Write("\";\r\n\r\n                    connection.Open();\r\n                    affectedRows = " +
                    "await command.ExecuteNonQueryAsync();\r\n                }\r\n            }\r\n\r\n     " +
                    "       return affectedRows;\r\n        }\r\n\r\n");
            
            #line 506 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"

    }

            
            #line default
            #line hidden
            this.Write("        /// <summary>Parses the ");
            
            #line 509 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write(" data model out of the reader.</summary>\r\n        /// <param name=\"reader\">The re" +
                    "ader.</param>\r\n        /// <returns>Populated ");
            
            #line 511 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write(" Data Model</returns>\r\n        private ");
            
            #line 512 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write("DataModel Parse");
            
            #line 512 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write("DataModel(IDataReader reader)\r\n        {\r\n            var data = new ");
            
            #line 514 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Record));
            
            #line default
            #line hidden
            this.Write("DataModel();\r\n            ");
            
            #line 515 "C:\git\VanillaDb\VanillaDb\DataProviders\SqlDataProvider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateReadFields()));
            
            #line default
            #line hidden
            this.Write("\r\n            return data;\r\n        }\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class SqlDataProviderBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
